nbaTeams = {
    "ATL": {
        "altCityName": "Atlanta",
        "city": "Atlanta",
        "confName": "East",
        "divName": "Southeast",
        "fullName": "Atlanta Hawks",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Hawks",
        "teamId": "1610612737",
        "teamShortName": "Atlanta",
        "tricode": "ATL",
        "urlName": "hawks"
    },
    "BKN": {
        "altCityName": "Brooklyn",
        "city": "Brooklyn",
        "confName": "East",
        "divName": "Atlantic",
        "fullName": "Brooklyn Nets",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Nets",
        "teamId": "1610612751",
        "teamShortName": "Brooklyn",
        "tricode": "BKN",
        "urlName": "nets"
    },
    "BOS": {
        "altCityName": "Boston",
        "city": "Boston",
        "confName": "East",
        "divName": "Atlantic",
        "fullName": "Boston Celtics",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Celtics",
        "teamId": "1610612738",
        "teamShortName": "Boston",
        "tricode": "BOS",
        "urlName": "celtics"
    },
    "CHA": {
        "altCityName": "Charlotte",
        "city": "Charlotte",
        "confName": "East",
        "divName": "Southeast",
        "fullName": "Charlotte Hornets",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Hornets",
        "teamId": "1610612766",
        "teamShortName": "Charlotte",
        "tricode": "CHA",
        "urlName": "hornets"
    },
    "CHI": {
        "altCityName": "Chicago",
        "city": "Chicago",
        "confName": "East",
        "divName": "Central",
        "fullName": "Chicago Bulls",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Bulls",
        "teamId": "1610612741",
        "teamShortName": "Chicago",
        "tricode": "CHI",
        "urlName": "bulls"
    },
    "CLE": {
        "altCityName": "Cleveland",
        "city": "Cleveland",
        "confName": "East",
        "divName": "Central",
        "fullName": "Cleveland Cavaliers",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Cavaliers",
        "teamId": "1610612739",
        "teamShortName": "Cleveland",
        "tricode": "CLE",
        "urlName": "cavaliers"
    },
    "DAL": {
        "altCityName": "Dallas",
        "city": "Dallas",
        "confName": "West",
        "divName": "Southwest",
        "fullName": "Dallas Mavericks",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Mavericks",
        "teamId": "1610612742",
        "teamShortName": "Dallas",
        "tricode": "DAL",
        "urlName": "mavericks"
    },
    "DEN": {
        "altCityName": "Denver",
        "city": "Denver",
        "confName": "West",
        "divName": "Northwest",
        "fullName": "Denver Nuggets",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Nuggets",
        "teamId": "1610612743",
        "teamShortName": "Denver",
        "tricode": "DEN",
        "urlName": "nuggets"
    },
    "DET": {
        "altCityName": "Detroit",
        "city": "Detroit",
        "confName": "East",
        "divName": "Central",
        "fullName": "Detroit Pistons",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Pistons",
        "teamId": "1610612765",
        "teamShortName": "Detroit",
        "tricode": "DET",
        "urlName": "pistons"
    },
    "GSW": {
        "altCityName": "Golden State",
        "city": "Golden State",
        "confName": "West",
        "divName": "Pacific",
        "fullName": "Golden State Warriors",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Warriors",
        "teamId": "1610612744",
        "teamShortName": "Golden State",
        "tricode": "GSW",
        "urlName": "warriors"
    },
    "HOU": {
        "altCityName": "Houston",
        "city": "Houston",
        "confName": "West",
        "divName": "Southwest",
        "fullName": "Houston Rockets",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Rockets",
        "teamId": "1610612745",
        "teamShortName": "Houston",
        "tricode": "HOU",
        "urlName": "rockets"
    },
    "IND": {
        "altCityName": "Indiana",
        "city": "Indiana",
        "confName": "East",
        "divName": "Central",
        "fullName": "Indiana Pacers",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Pacers",
        "teamId": "1610612754",
        "teamShortName": "Indiana",
        "tricode": "IND",
        "urlName": "pacers"
    },
    "LAC": {
        "altCityName": "LA Clippers",
        "city": "LA",
        "confName": "West",
        "divName": "Pacific",
        "fullName": "LA Clippers",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Clippers",
        "teamId": "1610612746",
        "teamShortName": "LA Clippers",
        "tricode": "LAC",
        "urlName": "clippers"
    },
    "LAL": {
        "altCityName": "Los Angeles Lakers",
        "city": "Los Angeles",
        "confName": "West",
        "divName": "Pacific",
        "fullName": "Los Angeles Lakers",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Lakers",
        "teamId": "1610612747",
        "teamShortName": "L.A. Lakers",
        "tricode": "LAL",
        "urlName": "lakers"
    },
    "MEM": {
        "altCityName": "Memphis",
        "city": "Memphis",
        "confName": "West",
        "divName": "Southwest",
        "fullName": "Memphis Grizzlies",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Grizzlies",
        "teamId": "1610612763",
        "teamShortName": "Memphis",
        "tricode": "MEM",
        "urlName": "grizzlies"
    },
    "MIA": {
        "altCityName": "Miami",
        "city": "Miami",
        "confName": "East",
        "divName": "Southeast",
        "fullName": "Miami Heat",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Heat",
        "teamId": "1610612748",
        "teamShortName": "Miami",
        "tricode": "MIA",
        "urlName": "heat"
    },
    "MIL": {
        "altCityName": "Milwaukee",
        "city": "Milwaukee",
        "confName": "East",
        "divName": "Central",
        "fullName": "Milwaukee Bucks",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Bucks",
        "teamId": "1610612749",
        "teamShortName": "Milwaukee",
        "tricode": "MIL",
        "urlName": "bucks"
    },
    "MIN": {
        "altCityName": "Minnesota",
        "city": "Minnesota",
        "confName": "West",
        "divName": "Northwest",
        "fullName": "Minnesota Timberwolves",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Timberwolves",
        "teamId": "1610612750",
        "teamShortName": "Minnesota",
        "tricode": "MIN",
        "urlName": "timberwolves"
    },
    "NOP": {
        "altCityName": "New Orleans",
        "city": "New Orleans",
        "confName": "West",
        "divName": "Southwest",
        "fullName": "New Orleans Pelicans",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Pelicans",
        "teamId": "1610612740",
        "teamShortName": "New Orleans",
        "tricode": "NOP",
        "urlName": "pelicans"
    },
    "NYK": {
        "altCityName": "New York",
        "city": "New York",
        "confName": "East",
        "divName": "Atlantic",
        "fullName": "New York Knicks",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Knicks",
        "teamId": "1610612752",
        "teamShortName": "New York",
        "tricode": "NYK",
        "urlName": "knicks"
    },
    "OKC": {
        "altCityName": "Oklahoma City",
        "city": "Oklahoma City",
        "confName": "West",
        "divName": "Northwest",
        "fullName": "Oklahoma City Thunder",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Thunder",
        "teamId": "1610612760",
        "teamShortName": "Oklahoma City",
        "tricode": "OKC",
        "urlName": "thunder"
    },
    "ORL": {
        "altCityName": "Orlando",
        "city": "Orlando",
        "confName": "East",
        "divName": "Southeast",
        "fullName": "Orlando Magic",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Magic",
        "teamId": "1610612753",
        "teamShortName": "Orlando",
        "tricode": "ORL",
        "urlName": "magic"
    },
    "PHI": {
        "altCityName": "Philadelphia",
        "city": "Philadelphia",
        "confName": "East",
        "divName": "Atlantic",
        "fullName": "Philadelphia 76ers",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "76ers",
        "teamId": "1610612755",
        "teamShortName": "Philadelphia",
        "tricode": "PHI",
        "urlName": "sixers"
    },
    "PHX": {
        "altCityName": "Phoenix",
        "city": "Phoenix",
        "confName": "West",
        "divName": "Pacific",
        "fullName": "Phoenix Suns",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Suns",
        "teamId": "1610612756",
        "teamShortName": "Phoenix",
        "tricode": "PHX",
        "urlName": "suns"
    },
    "POR": {
        "altCityName": "Portland",
        "city": "Portland",
        "confName": "West",
        "divName": "Northwest",
        "fullName": "Portland Trail Blazers",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Trail Blazers",
        "teamId": "1610612757",
        "teamShortName": "Portland",
        "tricode": "POR",
        "urlName": "blazers"
    },
    "SAC": {
        "altCityName": "Sacramento",
        "city": "Sacramento",
        "confName": "West",
        "divName": "Pacific",
        "fullName": "Sacramento Kings",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Kings",
        "teamId": "1610612758",
        "teamShortName": "Sacramento",
        "tricode": "SAC",
        "urlName": "kings"
    },
    "SAS": {
        "altCityName": "San Antonio",
        "city": "San Antonio",
        "confName": "West",
        "divName": "Southwest",
        "fullName": "San Antonio Spurs",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Spurs",
        "teamId": "1610612759",
        "teamShortName": "San Antonio",
        "tricode": "SAS",
        "urlName": "spurs"
    },
    "TOR": {
        "altCityName": "Toronto",
        "city": "Toronto",
        "confName": "East",
        "divName": "Atlantic",
        "fullName": "Toronto Raptors",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Raptors",
        "teamId": "1610612761",
        "teamShortName": "Toronto",
        "tricode": "TOR",
        "urlName": "raptors"
    },
    "UTA": {
        "altCityName": "Utah",
        "city": "Utah",
        "confName": "West",
        "divName": "Northwest",
        "fullName": "Utah Jazz",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Jazz",
        "teamId": "1610612762",
        "teamShortName": "Utah",
        "tricode": "UTA",
        "urlName": "jazz"
    },
    "WAS": {
        "altCityName": "Washington",
        "city": "Washington",
        "confName": "East",
        "divName": "Southeast",
        "fullName": "Washington Wizards",
        "isAllStar": False,
        "isNBAFranchise": True,
        "nickname": "Wizards",
        "teamId": "1610612764",
        "teamShortName": "Washington",
        "tricode": "WAS",
        "urlName": "wizards"
    }
}